# Generated by Django 6.1.1 on 2026-09-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_bill_order_products_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
