# Generated by Django 6.1.1 on 2026-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_use_producttype_through'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
