# Generated by Django 6.1.1 on 2026-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_customer_options_customer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(error_messages='hoppla', help_text='max 30 letters', max_length=30),
        ),
    ]
